parameters:
#    photograph_photo.example.class: Photograph\PhotoBundle\Example

services:
#    photograph_photo.example:
#        class: %photograph_photo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
 